### ISSUE TITLE
Feature Request - Siri, Add shortcut, VPN, Toggle VPN

### ISSUE THREAD

**Issue by m-hume** [passepartoutvpn/passepartout#343] opened 2023-09-08 08:37 UTC
# Summary
Would it be possible to add an extra item to the Siri - Add shortcut - VPN menu to toggle the state of the VPN?

Thanks

**Comment by keeshux** [comment] 2023-09-10 10:07
You have it already, or I don’t understand the question.

**Comment by m-hume** [comment] 2023-09-10 13:45
Currently you can add siri shortcut to Enable the VPN and a second shortcut to Disable the VPN
A single toggle shortcut would change the VPN to the opposite state

### [toggle](https://www.google.com/search?q=toggle+meaning)
switch from one effect, feature, or state to another by using a toggle.
"the play/pause button toggles between those functions"

**Comment by keeshux** [comment] 2023-09-10 13:52
Ah, I see now! Fair.

**Comment by keeshux** [comment] 2024-10-01 06:33
Duplicate of #610

**Closed by keeshux** 2024-10-01 06:33 UTC
Labels: enhancement
