### ISSUE TITLE
REQUEST: Multiple VPN Sources Active

### ISSUE THREAD

**Issue by GitPuffy** [passepartoutvpn/passepartout#488] opened 2024-01-29 20:47 UTC
I have a feature request, to allow the app to have multiple VPN connections active at one time.  My reasoning is the following.

I have two connections on that uses Wireguard and one that uses OpenVPN to two different VPN “servers.”

I would like to have one connection setup as the typical “Exclude” on-demand policy.  The other I would like to have set as an “Include” on-demand policy.

I have been in scenarios where some networks use deep packet investigation and block my Wireguard VPN connection.  I then manually stop that VPN connection in Passepeartout and manually turn on my OpenVPN connection (which is configured on TCP port 443) and have been able to connect my VPN that way.  It would be nice if I could have a configuration of a known network that is configured as an Include policy on my OpenVPN configuration in Passepartout I would then add those networks that block the Wireguard VPN to my OpenVPN include. 

I tried to set this up but when I went to enable the “second” connection, the include connection, my Wireguard VPN entry was set to disabled.

I hope I was able to explain my request and scenario in logical way.  Thank you for considering this.

**Comment by keeshux** [comment] 2024-02-03 10:56
If this is a feature request, then why mark it as a bug? :-)

By the way, it's the expected OS behavior and I'm afraid there's no workaround. Also a duplicate of #218, but I'll keep this open just in case I come up with something.

Thanks for the reminder, it'd actually be a great feature.

**Comment by GitPuffy** [comment] 2024-02-05 20:56
Sorry about marking a feature request as a bug.  Opps.  

Great to hear that you may have a solution for this request.  If you would like a tester for it please reach out.

Thank you

**Comment by juev** [comment] 2024-02-06 11:56
A very interesting change, it would be great if it were possible to implement such a thing.

**Comment by keeshux** [comment] 2024-11-05 13:18
Duplicate of #218, follow up there.

**Closed by keeshux** 2024-11-05 13:18 UTC
Labels: enhancement
