### ISSUE TITLE
Facing 'Update Required' Issue in VPN Settings after Configuration Setup

### ISSUE THREAD

**Issue by faisalferoz01** [passepartoutvpn/passepartout#498] opened 2024-05-03 10:11 UTC
Hello everyone,

I'm encountering an issue with my application where it's prompting me to update before I can connect the configuration file. This problem surfaced after I configured the settings. Here are the specifics:

- Xcode: 15.3
- Swift Version: 5.10
- Minimum Deployment Version: 15.0

Despite these configurations, the application insists on an update before allowing the connection to the configuration file. I've tried troubleshooting, but haven't found a solution yet.

Any guidance or insights on how to resolve this issue would be greatly appreciated.

Thank you.

![Screenshot 2024-05-03 at 2 56 38 PM](https://github.com/passepartoutvpn/passepartout-app/assets/105682097/17d89e0f-981a-438c-9e58-bae4305dbfdf)

**Comment by keeshux** [comment] 2024-09-28 13:52
Duplicate of https://github.com/passepartoutvpn/tunnelkit/issues/149

**Closed by keeshux** 2024-09-28 13:52 UTC
Labels: bug
